{
 "title": "Flask App",
 "time": { "from": "2025-07-25T18:58:41.899Z", "to": "2025-07-26T00:49:06.596Z" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins pod total CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container_name, pod_name) (\n  rate(container_cpu_usage_seconds_total{namespace=\"jenkins\", container_name!=\"POD\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} - node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "description": "for incoming and outgoing traffic",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "to monitor disk subsystem activity",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}